---
swagger: 2.0
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    product:
      description: Selected Document's unique handle value
      in: path
      name: product
      required: true
      schema:
        type: string
  schemas:
    User:
      properties:
        user_id:
          description: user ID
          type: string
        email:
          description: email
          type: string
        password:
          description: password
          type: string
        name:
          description: name
          type: string
        timestamp:
          description: timestamp
          type: Datetime
      required:
      - user_id
      - email
      - password
      type: object
    LogFile:
      properties:
        user_id:
          description: Document summary
          type: string
        document_id:
          description: Document ID
          type: string
        document_name:
          description: Document Name
          type: string
        chat_id:
          description: Chat ID
          type: string
        document:
          description: LogFile
          type: string
        document_summary:
          description: Document Summary
          type: string
        document_tag:
          description: Document tag
          type: string
        timestamp:
          description: timestamp
          type: Datetime
      required:
      - user_id
      - document_id
      - document_name
      - chat_id
      - document_tag
      type: object
    Small-Talk:
      properties:
        patterns:
          description: Small Talk Patterns
          type: array
        responses:
          description: Document tag
          type: array
      type: object
    Chat:
      properties:
        user_id:
          description: Document summary
          type: string
        document_id:
          description: Document ID
          type: string
        chat_id:
          description: Chat ID
          type: string
        query:
          description: Query for LogBot
          type: string
        response:
          description: Chat ID
          type: string
        timestamp:
          description: timestamp
          type: Datetime
      required:
      - user_id
      - chat_id
      - response
      type: object
  securitySchemes:
    logBotKey:
      type: apiKey
      name: x-access-token
      in: header
info:
  title: Producthub Example
  version: 0.0.1
  description: |
    This is an API example used in the Programmable Web Project course.
    It stores data about product and where they have been deployed.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: pwp-course@lists.oulu.fi
    name: PWP Staff List
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html