---
swagger: 2.0
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    product:
      description: Selected Document's unique handle value
      in: path
      name: product
      required: true
      schema:
        type: string
  schemas:
    Product:
      properties:
        weight:
          description: Document summary
          type: number
        price:
          description: Document tag
          type: number
      required:
      - handle
      - weight
      - price
      type: object
  securitySchemes:
    producthubKey:
      type: apiKey
      name: Producthub-Api-Key
      in: header
info:
  title: Producthub Example
  version: 0.0.1
  description: |
    This is an API example used in the Programmable Web Project course.
    It stores data about product and where they have been deployed.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: pwp-course@lists.oulu.fi
    name: PWP Staff List
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /products/:
    get:
      description: Get the list of managed Products and information
      responses:
        '200':
          description: List of Products with info
          content:
            application/json:
              example:
              - handle: test-product-1
                weight: 55
                price: 5
              - handle: test-product-2
                weight: 55
                price: 5
    post:
      description: Create a new product
      requestBody:
        description: JSON document that contains basic data for a new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              handle: new-test-product-1
              weight: 55
              price: 5
      responses:
        '201':
          description: The product was created successfully
          headers:
            Location: 
              description: URI of the new product
              schema: 
                type: string
        '400':
          description: The request body was not valid
        '409':
          description: A product with the same handle already exists
        '415':
          description: Wrong media type was used